languageCode = "en"
languageName = "English"
weight = 1

title = "Got Bacon?"
# copyright = "Copy, _right?_ :thinking_face:"

[params]
  isoCode = "en"
  displayName = "EN"
  rtl = false

  dateFormat = "2006-01-02"

  # mainSections = ["section1", "section2"]
   description = "My awesome website"

[author]
   name = "Madeline Bacon"
   image = "img/author.jpg"
   headline = "I'm only human"
   bio = "I'm a goofball"
   links = [
     { email = "mailto:madebacon00000@gmail.com" },
   ]
